FreeBSD:
  tags:
    - FreeBSD
  stage: build
  script:
    - if [ -d build ]; then rm -rf build ; fi
    - mkdir build
    - cd build ; timeout 5m cmake generate -G Ninja .. ; timeout 5m ninja all basecode-configured
    - cd tests ; timeout 5m ./tests.sh

Ubuntu:
  tags:
    - docker
  image: ubuntu:latest
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential gcc-8 g++-8 cmake ninja-build libncurses-dev
  script:
    - export CC=gcc-8
    - export CXX=g++-8
    - if [ -d build ]; then rm -rf build ; fi
    - mkdir build
    - cd build ; timeout 5m cmake generate -G Ninja .. ; timeout 20m ninja all basecode-configured
    - cd tests ; timeout 5m ./tests.sh
